# Generated by Django 4.2.7 on 2026-08-23 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='متن سؤال')),
                ('image', models.ImageField(blank=True, null=True, upload_to='question_bank/', verbose_name='تصویر سؤال')),
                ('option_a', models.CharField(max_length=500, verbose_name='گزینه A')),
                ('option_b', models.CharField(max_length=500, verbose_name='گزینه B')),
                ('option_c', models.CharField(max_length=500, verbose_name='گزینه C')),
                ('option_d', models.CharField(max_length=500, verbose_name='گزینه D')),
                ('correct_answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, verbose_name='پاسخ صحیح')),
                ('explanation', models.TextField(blank=True, null=True, verbose_name='پاسخ تشریحی')),
                ('subject', models.CharField(blank=True, max_length=100, null=True, verbose_name='درس')),
                ('topic', models.CharField(blank=True, max_length=100, null=True, verbose_name='مبحث')),
                ('difficulty', models.CharField(choices=[('easy', 'آسان'), ('medium', 'متوسط'), ('hard', 'سخت')], default='medium', max_length=10, verbose_name='سطح دشواری')),
                ('tags', models.CharField(blank=True, max_length=500, null=True, verbose_name='برچسب\u200cها')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط')),
            ],
            options={
                'verbose_name': 'سؤال بانک',
                'verbose_name_plural': 'بانک سؤالات',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['subject'], name='questions_q_subject_68a6aa_idx'), models.Index(fields=['topic'], name='questions_q_topic_fa384a_idx'), models.Index(fields=['difficulty'], name='questions_q_difficu_167a22_idx')],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='متن سؤال')),
                ('image', models.ImageField(blank=True, null=True, upload_to='questions/', verbose_name='تصویر سؤال')),
                ('option_a', models.CharField(max_length=500, verbose_name='گزینه A')),
                ('option_b', models.CharField(max_length=500, verbose_name='گزینه B')),
                ('option_c', models.CharField(max_length=500, verbose_name='گزینه C')),
                ('option_d', models.CharField(max_length=500, verbose_name='گزینه D')),
                ('correct_answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, verbose_name='پاسخ صحیح')),
                ('explanation', models.TextField(blank=True, null=True, verbose_name='پاسخ تشریحی')),
                ('subject', models.CharField(blank=True, max_length=100, null=True, verbose_name='درس')),
                ('topic', models.CharField(blank=True, max_length=100, null=True, verbose_name='مبحث')),
                ('difficulty', models.CharField(choices=[('easy', 'آسان'), ('medium', 'متوسط'), ('hard', 'سخت')], default='medium', max_length=10, verbose_name='سطح دشواری')),
                ('tags', models.CharField(blank=True, max_length=500, null=True, verbose_name='برچسب\u200cها')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_questions', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exams.exam', verbose_name='آزمون')),
            ],
            options={
                'verbose_name': 'سؤال',
                'verbose_name_plural': 'سؤالات',
                'ordering': ['exam', 'order', 'id'],
                'indexes': [models.Index(fields=['exam', 'order'], name='questions_q_exam_id_87fac9_idx'), models.Index(fields=['subject'], name='questions_q_subject_d73015_idx'), models.Index(fields=['difficulty'], name='questions_q_difficu_5db314_idx')],
            },
        ),
    ]
