# Generated by Django 4.2.7 on 2026-08-23 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان آزمون')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('start_datetime', models.DateTimeField(verbose_name='زمان شروع دسترسی')),
                ('end_datetime', models.DateTimeField(verbose_name='زمان پایان دسترسی')),
                ('duration_minutes', models.PositiveIntegerField(verbose_name='مدت آزمون (دقیقه)')),
                ('result_release_datetime', models.DateTimeField(help_text='نتایج قبل از این زمان قابل مشاهده نخواهند بود.', verbose_name='زمان انتشار نتایج')),
                ('is_published', models.BooleanField(default=False, verbose_name='منتشر شده')),
                ('show_correct_answers', models.BooleanField(default=True, help_text='آیا پاسخ\u200cهای صحیح پس از انتشار نتایج نمایش داده شوند؟', verbose_name='نمایش پاسخ\u200cهای صحیح')),
                ('show_explanations', models.BooleanField(default=True, help_text='آیا پاسخ تشریحی پس از انتشار نتایج نمایش داده شود؟', verbose_name='نمایش پاسخ تشریحی')),
                ('shuffle_questions', models.BooleanField(default=False, verbose_name='ترتیب تصادفی سؤالات')),
                ('shuffle_options', models.BooleanField(default=False, verbose_name='ترتیب تصادفی گزینه\u200cها')),
                ('negative_marking_enabled', models.BooleanField(default=False, help_text='آیا نمره منفی اعمال شود؟', verbose_name='نمره منفی فعال')),
                ('negative_marking_ratio', models.FloatField(default=3.0, help_text='هر چند پاسخ غلط = حذف یک پاسخ صحیح (پیش\u200cفرض: 3)', verbose_name='ضریب نمره منفی')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_exams', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط')),
                ('target_classes', models.ManyToManyField(blank=True, help_text='خالی بودن به معنای دسترسی همه دانش\u200cآموزان است.', related_name='exams', to='accounts.class', verbose_name='کلاس\u200cهای هدف')),
            ],
            options={
                'verbose_name': 'آزمون',
                'verbose_name_plural': 'آزمون\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('exam_published', 'آزمون جدید منتشر شد'), ('result_released', 'نتیجه آزمون منتشر شد'), ('exam_reminder', 'یادآوری آزمون')], max_length=20)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='exams.exam')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'اعلان',
                'verbose_name_plural': 'اعلان\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['start_datetime', 'end_datetime'], name='exams_exam_start_d_69dfd9_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['is_published'], name='exams_exam_is_publ_c23991_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['result_release_datetime'], name='exams_exam_result__452e51_idx'),
        ),
    ]
